#!/usr/bin/env bash

# Deno
asdf plugin add deno https://github.com/asdf-community/asdf-deno.git
asdf install deno latest
asdf global deno latest

# Go
asdf plugin add golang https://github.com/kennyp/asdf-golang.git
asdf install golang latest
asdf global golang latest

# Lua
asdf plugin add lua https://github.com/Stratus3D/asdf-lua.git
asdf install lua latest
asdf global lua latest

# Node
asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

# pnpm
asdf plugin add pnpm https://github.com/jonathanmorley/asdf-pnpm.git
asdf install pnpm latest
asdf global pnpm latest

asdf

# Python
asdf plugin add python
asdf install python latest
asdf global python latest

# Ruby
asdf plugin add ruby
asdf install ruby latest
asdf global ruby latest

# Rust
asdf plugin add rust https://github.com/asdf-community/asdf-rust.git
asdf install rust latest
asdf global rust latest

# Terraform
asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf install terraform latest
asdf global terraform latest

# Yarn
asdf plugin add yarn
asdf install yarn 1.22.19
asdf global yarn 1.22.19
