#!/usr/bin/env bash

set -e

remove() {
    local packages=("$@")

    echo "Uninstalling specified packages..."
    for package in "${packages[@]}"; do
        echo "Removing $package..."
        sudo dnf remove -y "$package"
    done
    echo "Uninstallation complete."
}

install() {
    local package_manager="$1"
    shift
    local packages=("$@")

    echo "Installing packages using $package_manager..."
    for package in "${packages[@]}"; do
        echo "Installing $package..."
        if [ "$package_manager" == "dnf" ]; then
            sudo dnf install -y "$package"
        elif [ "$package_manager" == "flatpak" ]; then
            flatpak install -y flathub "$package"
        fi
    done
}

packages_to_remove=(
    "gnome-boxes"
    "gnome-calendar"
    "gnome-clocks"
    "gnome-contacts"
    "gnome-maps"
    "gnome-text-editor"
    "gnome-tour"
    "gnome-weather"
    "media-writer"
    "rhythmbox"
    "simple-scan"
    "yelp"
)

flatpak_applications=(
    "com.jetbrains.IntelliJ-IDEA-Ultimate"
    "com.slack.Slack"
    "com.spotify.Client"
    "org.mozilla.firefox"
    "org.videolan.VLC"
)

remove "${packages_to_remove[@]}"

echo "Updating the system..."
sudo dnf update -y

if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/Brewfile" ]; then
    echo "Installing brew dependencies..."
    brew bundle
fi

if ! command -v flatpak &> /dev/null; then
    echo "Installing Flatpak..."
    sudo dnf install -y flatpak
    echo "Adding Flathub repository..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi

install "flatpak" "${flatpak_applications[@]}"

echo "Cleaning up unused dependencies..."
sudo dnf autoremove -y

echo "Done"