#!/usr/bin/env bash

set -e

packages_to_uninstall=(
  "gnome-boxes"
  "gnome-calendar"
  "gnome-clocks"
  "gnome-contacts"
  "gnome-maps"
  "gnome-text-editor"
  "gnome-tour"
  "gnome-weather"
  "media-writer"
  "rhythmbox"
  "simple-scan"
  "yelp"
)

echo "Uninstalling specified packages..."
for package in "${packages_to_uninstall[@]}"
do
    echo "Removing $package..."
    sudo dnf remove -y "$package"
done
echo "Uninstallation complete."

echo "Updating the system..."
sudo dnf update -y


if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/Brewfile" ]; then
  echo "Updating homebrew bundle..."
  brew bundle
fi

if ! command -v flatpak &> /dev/null
then
    echo "Flatpak not found. Installing Flatpak..."
    sudo dnf install -y flatpak
    echo "Adding Flathub repository..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
else
    echo "Flatpak is already installed."
fi

flatpak_applications=(
    "com.jetbrains.IntelliJ-IDEA-Ultimate"
    "com.slack.Slack"
    "com.spotify.Client"
    "org.mozilla.firefox"
    "org.videolan.VLC"
)

echo "Installing Flatpak applications..."
for app in "${flatpak_applications[@]}"
do
    echo "Installing $app via Flatpak..."
    flatpak install -y flathub "$app"
done

echo "Cleaning up unused dependencies..."
sudo dnf autoremove -y