#!/usr/bin/env bash

set -e

GNOME_SHELL_VERSION=$(gnome-shell --version | cut -d' ' -f3 | cut -d'.' -f1,2)

echo "Installing GNOME extensions..."

extensions=(
    ("dash-to-dock" "dash-to-dock@micxgx.gmail.com" "https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v${GNOME_SHELL_VERSION}.shell-extension.zip")
)

for extension in "${extensions[@]}"; do
    name="${extension[0]}"
    package="${extension[1]}"
    repo="${extension[2]}"
    wget -O "/tmp/${name}.zip" "$repo"
    gnome-extensions install -f "/tmp/${name}.zip"
    gnome-extensions enable "$package"
    rm "/tmp/${name}.zip"
done

echo "Configuring GNOME extensions..."

# Dash to Dock
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed true
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED

echo "Configuring GNOME settings..."

# Set time zone automatically based on location
gsettings set org.gnome.system.location enabled true

# Disable GNOME usage data collection
gsettings set org.gnome.desktop.privacy send-software-usage-stats false
gsettings set org.gnome.desktop.privacy report-technical-problems false

# Require immediate password after sleep/screen saver
gsettings set org.gnome.desktop.screensaver lock-enabled true
gsettings set org.gnome.desktop.screensaver lock-delay 0

# Always show scroll bars
gsettings set org.gnome.desktop.interface overlay-scrolling false

# Disable natural scrolling
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false

# Enable touchpad click emulation in fingers mode
gsettings set org.gnome.desktop.peripherals.touchpad click-method 'fingers'

# Disable animations
gsettings set org.gnome.desktop.interface enable-animations false

# Disable workspaces
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 1

# Reset the app picker layout to sort applications alphabetically
gsettings set org.gnome.shell app-picker-layout "[]"

# Disable screen brightness auto-adjustment
gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled false

# Disable alert sounds
gsettings set org.gnome.desktop.sound event-sounds false

echo "Done"