#!/usr/bin/env bash

set -e

src='#!/bin/sh
open -na "IntelliJ IDEA.app" --args "$@"'

echo "$src" | sudo tee /usr/local/bin/idea

sudo chmod +x /usr/local/bin/idea

if [[ "$OSTYPE" == "linux"* ]]; then
	echo "fs.inotify.max_user_watches = 1048576" > /etc/sysctl.d/idea.conf
	sysctl -p /etc/sysctl.d/idea.conf
fi

echo "Done"
