#!/usr/bin/env bash

set -e

if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/Brewfile" ]; then
  echo "Installing homebrew dependencies..."
  brew bundle
fi

echo "Done"
