#!/usr/bin/env bash

set -e

# Lua
mise plugin add lua https://github.com/Stratus3D/asdf-lua.git
mise install lua latest
mise global lua latest

# Node
mise plugin add nodejs
mise install nodejs latest
mise global nodejs latest

# pnpm
mise plugin add pnpm https://github.com/jonathanmorley/asdf-pnpm.git
mise install pnpm latest
mise global pnpm latest

# Terraform
mise plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
mise install terraform latest
mise global terraform latest

# Yarn
mise plugin add yarn
mise install yarn latest
mise global yarn latest

echo "Done"
