#!/usr/bin/env bash

set -e

mise use bun@1 --global
mise use go@1.24 --global
mise use lua@5.4 --global
mise use node@22 --global
mise use pnpm@10 --global
mise use ruby@3.4 --global
mise use terraform@1.11 --global
mise use yarn@1.22 --global

echo "Done"
