#!/usr/bin/env bash

set -e

# Lua
mise plugin add lua https://github.com/Stratus3D/asdf-lua.git
mise install lua@5.4
mise use lua@5.4 --global

# Node
mise use node@22 --global

# pnpm
mise plugin add pnpm https://github.com/jonathanmorley/asdf-pnpm.git
mise install pnpm@10
mise use pnpm@10 --global

# Terraform
mise plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
mise install terraform@1.11
mise use terraform@1.11 --global

# Yarn
mise plugin add yarn
mise install yarn@1.22
mise use yarn@1.22 --global

echo "Done"
