#!/usr/bin/env bash

set -e

npm install -g @nestjs/cli
npm install -g degit
npm install -g eas-cli
npm install -g firebase-tools
npm install -g http-server
npm install -g npm-check-updates
npm install -g prettier

echo "Done"
