#!/usr/bin/env bash

set -e

junk_applications=(
    "gnome-boxes"
    "gnome-calendar"
    "gnome-clocks"
    "gnome-contacts"
    "gnome-maps"
    "gnome-shell-extension-ubuntu-dock"
    "gnome-text-editor"
    "gnome-tour"
    "gnome-weather"
    "rhythmbox"
    "simple-scan"
    "yelp"
)

declare -A apt_applications
apt_applications=(
    ["curl"]=""
    ["file"]=""
    ["git"]=""
    ["build-essential"]=""
    ["procps"]=""
    ["yadm"]=""
    ["gnome-shell-extensions"]=""
    ["gnome-tweaks"]=""
    ["gnome-shell-extension-manager"]=""
    ["ulauncher"]="ppa:agornostal/ulauncher"
)

flatpak_applications=(
    "com.jetbrains.IntelliJ-IDEA-Ultimate"
    "com.slack.Slack"
    "com.spotify.Client"
    "org.mozilla.firefox"
    "org.videolan.VLC"
)

# Function to check if a package is installed
is_installed() {
    dpkg -s "$1" &> /dev/null
}

# Remove junk applications
for package in "${junk_applications[@]}"; do
    if is_installed "$package"; then
        echo "Removing $package..."
        sudo apt remove -y "$package"
    else
        echo "$package is not installed. Skipping..."
    fi
done

sudo apt update && sudo apt upgrade -y

# Install APT applications
for name in "${!apt_applications[@]}"; do
    repo=${apt_applications[$name]}
    if ! is_installed "$name"; then
        if [ -n "$repo" ]; then
            sudo add-apt-repository -y "$repo"
        fi
        echo "Installing $name..."
        sudo apt install -y "$name"
    else
        echo "$name is already installed. Skipping..."
    fi
done

# Install Homebrew if not already installed
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed. Skipping..."
fi

if [ -f "$HOME/Brewfile" ]; then
    brew bundle
fi

# Install Flatpak if not already installed
if ! command -v flatpak &> /dev/null; then
    echo "Installing Flatpak..."
    sudo apt install -y flatpak
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
else
    echo "Flatpak is already installed. Skipping..."
fi

# Install Flatpak applications
for app in "${flatpak_applications[@]}"; do
    if ! flatpak list | grep -q "$app"; then
        echo "Installing $app..."
        flatpak install -y flathub "$app"
    else
        echo "$app is already installed. Skipping..."
    fi
done

sudo apt autoremove -y

echo "Done"